server:
  port: 10001
  servlet:
    context-path: /ss
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://aliyun:3306/kongfy?useUnicode=true&characterEncoding=UTF-8